development:
  adapter: mysql2
  encoding: utf8
  database: culini_development
  pool: 5
  username: root
  password:
  host: localhost
  reconnect: true

test:
  adapter: mysql2
  encoding: utf8
  database: culini_test
  pool: 5
  username: root
  password:
  host: localhost
  reconnect: true

production:
  adapter: mysql2
  encoding: utf8
  database: culini_production
  pool: 5
  username: root
  password:
  host: localhost
  reconnect: true
